In [ ]:
# 隣接発話間の変化量を計算

In [ ]:
import pandas as pd

df_L = pd.read_csv("/home/mitani/CSJ-emo-int_bunseki/csj_vad_bunseki/speaker_split_noise/speaker_L_cleaned.csv")
df_R = pd.read_csv("/home/mitani/CSJ-emo-int_bunseki/csj_vad_bunseki/speaker_split_noise/speaker_R_cleaned.csv")

In [32]:
df_L_vad = df_L[["filename", "text", "valence", "arousal", "dominance", "intensity_pred_kushinada"]]
df_L_vad.head()

,filename,text,valence,arousal,dominance,intensity_pred_kushinada
0,0001_L.wav,お願いします,0.41,0.32,0.39,3.85
1,0004_L.wav,今日はお疲れ様でした,0.52,0.39,0.40,2.29
2,0006_L.wav,どうでしたか,0.30,0.36,0.40,0.76
3,0007_L.wav,緊張します,0.64,0.41,0.46,1.98
4,0009_L.wav,<笑>,0.66,0.65,0.57,2.34

In [33]:
df_R_vad = df_R[["filename", "text", "valence", "arousal", "dominance", "intensity_pred_kushinada"]]
df_R_vad.head()

,filename,text,valence,arousal,dominance,intensity_pred_kushinada
0,0003_R.wav,お願いします,0.27,0.14,0.27,2.59
1,0005_R.wav,(F (? あ))お疲れ様でした,0.62,0.39,0.43,0.55
2,0008_R.wav,そうですね初めは凄い緊張しました,0.53,0.53,0.53,0.85
3,0010_R.wav,<笑>,0.83,0.72,0.66,3.75
4,0011_R.wav,けど私も(F あのー)例えば(D す)(F あのー)ここで録音している学会の(F あの)ビデ...,0.64,0.59,0.57,0.88

In [ ]:
# 隣接発話間の変化量を計算
df_L["delta_valence"] = df_L["valence"].diff().abs().round(2)       
df_L["delta_arousal"] = df_L["arousal"].diff().abs().round(2)
df_L["delta_dominance"] = df_L["dominance"].diff().abs().round(2)
df_L["delta_int_kushinada"] = df_L["intensity_pred_kushinada"].diff().abs().round(2)

df_R["delta_valence"] = df_R["valence"].diff().abs().round(2)
df_R["delta_arousal"] = df_R["arousal"].diff().abs().round(2)
df_R["delta_dominance"] = df_R["dominance"].diff().abs().round(2)
df_R["delta_int_kushinada"] = df_R["intensity_pred_kushinada"].diff().abs().round(2)

# 1行目は比較対象がないため削除(NaNになる)
df_diff_L = df_L.iloc[1:].copy()
df_diff_R = df_R.iloc[1:].copy()

In [42]:
# filename, text, delta類だけ抽出
df_L_delta = df_L[["filename", "text", "delta_valence", "delta_arousal", "delta_dominance", "delta_int_kushinada"]]
df_L_delta.head()

,filename,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0001_L.wav,お願いします,NaN,NaN,NaN,NaN
1,0004_L.wav,今日はお疲れ様でした,0.11,0.07,0.01,1.56
2,0006_L.wav,どうでしたか,0.22,0.03,0.00,1.53
3,0007_L.wav,緊張します,0.34,0.05,0.06,1.22
4,0009_L.wav,<笑>,0.02,0.24,0.11,0.36

In [43]:
df_R_delta = df_R[["filename", "text", "delta_valence", "delta_arousal", "delta_dominance", "delta_int_kushinada"]]
df_R_delta.head()

,filename,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0003_R.wav,お願いします,NaN,NaN,NaN,NaN
1,0005_R.wav,(F (? あ))お疲れ様でした,0.35,0.25,0.16,2.04
2,0008_R.wav,そうですね初めは凄い緊張しました,0.09,0.14,0.10,0.30
3,0010_R.wav,<笑>,0.30,0.19,0.13,2.90
4,0011_R.wav,けど私も(F あのー)例えば(D す)(F あのー)ここで録音している学会の(F あの)ビデ...,0.19,0.13,0.09,2.87

In [44]:
df_L.head()     # 確認(speaker_L_cleaned.csv + delta類)

,filename,emotion_izanami,intensity_pred_izanami,emotion_kushinada,intensity_pred_kushinada,valence,arousal,dominance,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0001_L.wav,DIS,3.49,ACC,3.85,0.41,0.32,0.39,お願いします,NaN,NaN,NaN,NaN
1,0004_L.wav,ANT,2.11,JOY,2.29,0.52,0.39,0.40,今日はお疲れ様でした,0.11,0.07,0.01,1.56
2,0006_L.wav,ANT,2.27,ANT,0.76,0.30,0.36,0.40,どうでしたか,0.22,0.03,0.00,1.53
3,0007_L.wav,ACC,2.04,ACC,1.98,0.64,0.41,0.46,緊張します,0.34,0.05,0.06,1.22
4,0009_L.wav,FEA,1.88,SUR,2.34,0.66,0.65,0.57,<笑>,0.02,0.24,0.11,0.36

In [45]:
# 保存
df_L.to_csv("data/vad_delta_L.csv", encoding="utf-8", index=False)
df_R.to_csv("data/vad_delta_R.csv", encoding="utf-8", index=False)

In [1]:
print("a")

a

In [2]:
# 絶対値を取らないバージョンも作成
import pandas as pd

df_L = pd.read_csv("/home/mitani/CSJ-emo-int_bunseki/csj_vad_bunseki/speaker_split_noise/speaker_L_cleaned.csv")
df_R = pd.read_csv("/home/mitani/CSJ-emo-int_bunseki/csj_vad_bunseki/speaker_split_noise/speaker_R_cleaned.csv")

# 隣接発話間の変化量を計算
df_L["delta_valence"] = df_L["valence"].diff().round(2)       
df_L["delta_arousal"] = df_L["arousal"].diff().round(2)
df_L["delta_dominance"] = df_L["dominance"].diff().round(2)
df_L["delta_int_kushinada"] = df_L["intensity_pred_kushinada"].diff().round(2)

df_R["delta_valence"] = df_R["valence"].diff().round(2)
df_R["delta_arousal"] = df_R["arousal"].diff().round(2)
df_R["delta_dominance"] = df_R["dominance"].diff().round(2)
df_R["delta_int_kushinada"] = df_R["intensity_pred_kushinada"].diff().round(2)

# 1行目は比較対象がないため削除(NaNになる)
df_diff_L = df_L.iloc[1:].copy()
df_diff_R = df_R.iloc[1:].copy()

# 保存
df_L.to_csv("data/vad_delta_L_no_abs.csv", encoding="utf-8", index=False)
df_R.to_csv("data/vad_delta_R_no_abs.csv", encoding="utf-8", index=False)