In [2]:
import pandas as pd

In [3]:
df_L = pd.read_csv("data/vad_delta_L.csv")
df_L.head()

,filename,emotion_izanami,intensity_pred_izanami,emotion_kushinada,intensity_pred_kushinada,valence,arousal,dominance,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0001_L.wav,DIS,3.49,ACC,3.85,0.41,0.32,0.39,お願いします,NaN,NaN,NaN,NaN
1,0004_L.wav,ANT,2.11,JOY,2.29,0.52,0.39,0.40,今日はお疲れ様でした,0.11,0.07,0.01,1.56
2,0006_L.wav,ANT,2.27,ANT,0.76,0.30,0.36,0.40,どうでしたか,0.22,0.03,0.00,1.53
3,0007_L.wav,ACC,2.04,ACC,1.98,0.64,0.41,0.46,緊張します,0.34,0.05,0.06,1.22
4,0009_L.wav,FEA,1.88,SUR,2.34,0.66,0.65,0.57,<笑>,0.02,0.24,0.11,0.36

In [4]:
df_R = pd.read_csv("data/vad_delta_R.csv")
df_R.head()

,filename,emotion_izanami,intensity_pred_izanami,emotion_kushinada,intensity_pred_kushinada,valence,arousal,dominance,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0003_R.wav,SAD,2.15,ACC,2.59,0.27,0.14,0.27,お願いします,NaN,NaN,NaN,NaN
1,0005_R.wav,SAD,2.15,SAD,0.55,0.62,0.39,0.43,(F (? あ))お疲れ様でした,0.35,0.25,0.16,2.04
2,0008_R.wav,ACC,0.12,ACC,0.85,0.53,0.53,0.53,そうですね初めは凄い緊張しました,0.09,0.14,0.10,0.30
3,0010_R.wav,SUR,-0.04,ACC,3.75,0.83,0.72,0.66,<笑>,0.30,0.19,0.13,2.90
4,0011_R.wav,ANT,1.58,ANT,0.88,0.64,0.59,0.57,けど私も(F あのー)例えば(D す)(F あのー)ここで録音している学会の(F あの)ビデ...,0.19,0.13,0.09,2.87

In [5]:
# データのサイズ
print(f"L(行, 列): {df_L.shape}")
print(f"R(行, 列): {df_R.shape}")

L(行, 列): (264, 13)
R(行, 列): (256, 13)

In [6]:
# filename, text, delta類だけ抽出
df_L_delta = df_L[["filename", "text", "delta_valence", "delta_arousal", "delta_dominance", "delta_int_kushinada"]]
df_L_delta.to_csv("data/delta_L.csv", encoding="utf-8", index=False)
df_L_delta.head()

,filename,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0001_L.wav,お願いします,NaN,NaN,NaN,NaN
1,0004_L.wav,今日はお疲れ様でした,0.11,0.07,0.01,1.56
2,0006_L.wav,どうでしたか,0.22,0.03,0.00,1.53
3,0007_L.wav,緊張します,0.34,0.05,0.06,1.22
4,0009_L.wav,<笑>,0.02,0.24,0.11,0.36

In [7]:
# filename, text, delta類だけ抽出
df_R_delta = df_R[["filename", "text", "delta_valence", "delta_arousal", "delta_dominance", "delta_int_kushinada"]]
df_R_delta.to_csv("data/delta_R.csv", encoding="utf-8", index=False)
df_R_delta.head()

,filename,text,delta_valence,delta_arousal,delta_dominance,delta_int_kushinada
0,0003_R.wav,お願いします,NaN,NaN,NaN,NaN
1,0005_R.wav,(F (? あ))お疲れ様でした,0.35,0.25,0.16,2.04
2,0008_R.wav,そうですね初めは凄い緊張しました,0.09,0.14,0.10,0.30
3,0010_R.wav,<笑>,0.30,0.19,0.13,2.90
4,0011_R.wav,けど私も(F あのー)例えば(D す)(F あのー)ここで録音している学会の(F あの)ビデ...,0.19,0.13,0.09,2.87

In [8]:
# パーセンタイル
print("----------L---------")
print("<delta_arousal>")
for p in [80, 85, 90, 95]:
    print(p, df_L["delta_valence"].quantile(p/100).round(2))
print("")

print("<delta_int>")
for p in [80, 85, 90, 95]:
    print(p, df_L["delta_int_kushinada"].quantile(p/100).round(2))
print("")

print("----------R------------")
print("<delta_arousal>")
for p in [80, 85, 90, 95]:
    print(p, df_R["delta_valence"].quantile(p/100).round(2))
print("")

print("<delta_int>")
for p in [80, 85, 90, 95]:
    print(p, df_R["delta_int_kushinada"].quantile(p/100).round(2))

----------L---------
<delta_arousal>
80 0.29
85 0.36
90 0.45
95 0.55

<delta_int>
80 2.43
85 2.9
90 3.29
95 4.06

----------R------------
<delta_arousal>
80 0.28
85 0.31
90 0.35
95 0.5

<delta_int>
80 1.92
85 2.04
90 2.46
95 2.94